### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by domenkozar** [ElvishJerricco/purescript-packages2nix#2]
Hey @ElvishJerricco could you describe here (or in README) the current status of this project? I'm interested to see how much work is needed to compile purescript-bridge based project :)

**Comment by ElvishJerricco** [comment]
The status is that this pretty much works. But for validation's sake, I do want to fix #1. I'll put up a README with a TODO section for this. I can't imagine it'd be too hard to have a Nix system for running `purescript-bridge` before using [purescript-modules](https://github.com/ElvishJerricco/nix-purescript-skeleton) (which is less stable and in need of work).

**Comment by domenkozar** [comment]
Thanks a quick getting started tutorial would be much appreciated :)

I'll give this a go very soon!

**Comment by ElvishJerricco** [comment]
Cool. I'll improve the README later tonight. Closing this issue.

**Comment by ElvishJerricco** [comment]
Readme should be at least slightly clearer now =P I moved the companion repo to a better URL: https://github.com/ElvishJerricco/nix-purescriptPackages. Haven't added anything like a tutorial, but it's just like `haskellPackages`, and there's an example in the `purescriptPackages` repo.

**Comment by domenkozar** [comment]
Thanks!
